### ISSUE TITLE
Implementaion of UI

### ISSUE THREAD

**Issue by roshan-eng** [jitinsingla/TetrahedralRepresentation#10]
Here's the initial overview i thought. Subject to changes on various inputs of extra functionalities or design change on all your advises.
![Untitled](https://github.com/jitinsingla/TetrahedralRepresentation/assets/77035385/99afeec8-d723-4b82-8261-b4bf44c29386)

I will be trying to figure out the coding part as soon as possible. @tomgoddard ,  you can share the resources to implement all those things mentioned here and if have any suggestions to changes then I am very likely to follow one.

**Comment by tomgoddard** [comment]
I'm not sure what the user interface panel should look like.  Usually we try to keep it simple where any advanced options (e.g. alpha, unit) only available by typing a command.  I think the user interface should let you choose the parts of a structure in a convenient way.  But I don't know what parts a user, such as someone on the USC Inner Space team, is likely to choose.  My sense is they want to make some parts of a chain using massing and some other parts use per-residue tetrahedra.  I'm not sure how they will want to divide up the chain.  So I suggest you first get the USC team using the command and then have them report to you the commands for specific PDB structures that they found useful.  That will tell you how they like to divide up the chains and will give an idea for the options a user interface panel should present.
