### ISSUE TITLE
Creating the command inputs for ChimeraX

### ISSUE THREAD

**Issue by roshan-eng** [jitinsingla/TetrahedralRepresentation#2]
Currently the inputs are taken form ChimeraX shell in a list and dictionary format. I don't have the idea of variable types ChimeraX supports to integrate this input via. ChimeraX command line. The current input requirements is in line 384.

@tomgoddard , please look if you can fix this.

**Comment by tomgoddard** [comment]
I am not able to run a simple example of massing().  Code seems to be missing.  Reported as issue #3.

**Comment by roshan-eng** [comment]
While looking at atoms in residues.atoms for ASN, i am getting ['N', 'CA', 'C', 'O']. How to get the c_beta chain in it ? @tomgoddard

**Comment by roshan-eng** [comment]
> I am not able to run a simple example of massing(). Code seems to be missing. Reported as issue #3.

I am doing some code cleaning that's why its broken for now. I will complete this by today.
