### ISSUE TITLE
Allow massing command to not create tetrahedra for non-massing residues

### ISSUE THREAD

**Issue by tomgoddard** [jitinsingla/TetrahedralRepresentation#5]
Currently the massing command makes tetrahedra for the residues that are not specified.  There should be an option to prevent this so I can create massing for just the specified residues and that is all.  For example

massing /A:1-100 tetra false

I would suggest the default should be that it not make tetra for residues that are not specified.

**Comment by jitinsingla** [comment]
Understood. Will do it.

**Comment by roshan-eng** [comment]
Solved !
