### ISSUE TITLE
Color tetrahedra and massing to match the residue colors

### ISSUE THREAD

**Issue by tomgoddard** [jitinsingla/TetrahedralRepresentation#6]
Currently all the tetrahedra are the same gray color.  It would be convenient if the tetrahedron colors matched the residue colors.  For massing the average color of the massed residues could be used.

**Comment by jitinsingla** [comment]
Can you please point us to documentation on how to fetch exiting color.
Also then if we want to give color to individual tetra different color, then how can we do it, because currently we add all tetrahedra  in a chain as a single model.

**Comment by tomgoddard** [comment]
To get the color of a residue used for showing ribbons use

    residue.ribbon_color

This gives a 4-tuple (red,green,blue,alpha) of unsigned 8-bit values (0-255).  Alpha is opacity, 255 for opaque.  See the ChimeraX Programming Manual under Python modules, atomic, for documentation of all atomic attributes, for instance,

    https://www.cgl.ucsf.edu/chimerax/docs/devel/modules/atomic/atomic.html#chimerax.atomic.cymol.CyResidue

To color individual tetrahedra you set the colors of the vertices of the tetrahedra.  If you tetrahedron model is m you set

    m.vertex_colors = colors

where colors is a numpy array of size (nvertices, 4) of type uint8 that has the (red, green, blue, alpha) values for each vertex.

**Comment by roshan-eng** [comment]
DONE !
