### ISSUE TITLE
Add a tetra ChimeraX command to make tetrahedron model

### ISSUE THREAD

**Issue by tomgoddard** [jitinsingla/TetrahedralRepresentation#7]
The ChimeraX tetra command should be easy to add following the massing command.

**Comment by roshan-eng** [comment]
@tomgoddard in the code you provided, i believe that there's no way to input for the chains parameter for massing from chimerax command-line. Should this be included at all or if so then how can it be done @jitinsingla ?

**Comment by roshan-eng** [comment]
DONE !

**Comment by tomgoddard** [comment]
I don't understand the purpose of the "chains" parameter of the massing() function.  If it just means do massing for the full sequence then the "sequence" parameter can do that and just using the command "massing /A" without specifying a limited residue range will do that now.
