### ISSUE TITLE
Put the tetrahedron/massing commands on the ChimeraX Toolshed

### ISSUE THREAD

**Issue by tomgoddard** [jitinsingla/TetrahedralRepresentation#8]
To allow people to easily install the tetrahedron and massing commands without having to open the Tetra.py code each time the start ChimeraX it would be useful to put a bundle on the ChimeraX Toolshed so it can be installed using ChimeraX menu Tools / More Tools with just a button press.  Then the commands would be available as soon as ChimeraX started.  And it would be very easy to get updates, in fact ChimeraX would tell users who have it installed when a new version is released.

Here is the Toolshed web site

https://cxtoolshed.rbvi.ucsf.edu

and here is a tutorial about how to put the code on the Toolshed

https://www.cgl.ucsf.edu/chimerax/docs/devel/tutorials/tutorial_command.html

and some general information

https://www.cgl.ucsf.edu/chimerax/docs/devel/tutorials/introduction.html

**Comment by jitinsingla** [comment]
Sure. Working on it.

**Comment by roshan-eng** [comment]
Done with building the bundles but not sure on how to distribute it. It was asking for some wheel format file. The current bundle file is committed to git under the folder name "tetrascape_cmd". Its running perfectly fine on installing locally.
@tomgoddard , have a look on it and fix this distribution problem.

**Comment by tomgoddard** [comment]
Now to make the wheel file that is used to distribute your command start ChimeraX and run the "devel install" command giving the tetrascape_cmd directory, for example,

    devel install ~/ucsf/tetra/tetrascape_cmd

Then the wheel file will be made

    tetrascape_cmd/dist/ChimeraX_TetraScapeCommand-0.1-py3-none-any.whl

That file can then be submitted to the ChimeraX Toolshed web page

    https://cxtoolshed.rbvi.ucsf.edu

after signing in with your Google account.  Once on the Toolshed, all ChimeraX users can install it using ChimeraX menu Tools / More Tools....

**Comment by tomgoddard** [comment]
It seems you have copied the Tetra.py code to tetraspace_cmd/src/cmd.py.  You should have only one copy of this code.  Already you have made changes to Tetra.py that are not in cmd.py.  The usual way of organizing the GitHub TetrahedralRepresentation repository for a ChimeraX command 

   README.md
   bundle_info.xml
   src/__init__.py
   src/Tetra.py

You would not have any tetrascape_cmd subdirectory and no duplication of the Tetra.py code.

**Comment by tomgoddard** [comment]
Your Tetra.py code requires PyPi packages alphashape and trimesh.  You need to specify those in the <Dependencies> section of your bundle_info.xml so ChimeraX installs them when your code is installed.

```
	<Dependencies> 
		<Dependency name = "ChimeraX-Core"/> 
		<Dependency name = "ChimeraX-Surface"/>
		<Dependency name = "alphashape"/>
		<Dependency name = "trimesh"/>
	</Dependencies>
```

**Comment by roshan-eng** [comment]
Fixed all the minor issues. Also submitted the bundle !

**Comment by tomgoddard** [comment]
Thanks!  I'm not able to install the bundle using ChimeraX Tools / More Tools... apparently because the bundle_info.xml needs to specify a ChimeraX version number.  I suggest you replace in bundle_info.xml

```
	<Dependencies> 
		<Dependency name = "ChimeraX-Core"/> 
		<Dependency name = "ChimeraX-Surface"/>
		<Dependency name = "alphashape"/>
		<Dependency name = "trimesh"/>
	</Dependencies>
```

with

```
	<Dependencies> 
		<Dependency name = "ChimeraX-Core" version="~=1.0"/> 
		<Dependency name = "ChimeraX-Surface" version="~=1.0"/>
		<Dependency name = "alphashape" version="==1.3.1"/>
		<Dependency name = "trimesh" version="==4.0.10"/>
	</Dependencies>
```

This will allow it to install with any ChimeraX 1.x version, and will also specify the exact versions of alphashape and trimesh it is known to work with.  Also update the version of the bundle by changing

```
<BundleInfo name = "ChimeraX-TetraScapeCommand" 
	version = "0.1" package = "tetrascape_cmd"
	minSessionVersion = "1" maxSessionVersion = "1">
```

to

```
<BundleInfo name = "ChimeraX-TetraScapeCommand" 
	version = "0.2" package = "tetrascape_cmd"
	minSessionVersion = "1" maxSessionVersion = "1">
```

and build a newer wheel with the ChimeraX devel install command.  Then Once you do this go to the ChimeraX Toolshed

    https://cxtoolshed.rbvi.ucsf.edu/apps/chimeraxtetrascapecommand

sign in with Google and click the Editor Actions menu and

**Comment by tomgoddard** [comment]
Continuing last comment...

Choose Editor Actions / Submit a bundle release to upload the new wheel.

You can also use Editor Actions / Edit this page to provide a description of how to use the command under "Details" and a screenshot of what the result looks like, and an icon for the bundle (say a tetrahedron icon).
